# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 365215abbebc4fcd800d7308843dfd9966ad0e048acbad322df5d9b86488aa08157aa28cc7fd5fb21d33534786e4a74f380404b5e9e193611186e58454b39b8c

test:
  secret_key_base: 5c09fd512a59c0d3784c763fed93fe022066e035fa62f721efbf1b21cfc05b3fe91ade36155a2b7089eb278df78b43dfa438194d8cbff127d54ae0d77a302701

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
